version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - '.env'
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis_volume:/data'
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq
    volumes:
      - '.:/myapp'
    env_file:
      - '.env'
  rss_service:
    image: sergeyberdnikovich/rss_reader
    command: make run
  web:
    image: sergeyberdnikovich/rss_posts_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
      - rss_service
    env_file:
      - '.env'

volumes:
  redis_volume:
  postgres_volume:
