default: &default
  rss_service:
    host: 'http://localhost:8081'
    auth_path: '/authenticate'
    login: 'TestRssApp'
    password: 'password'

development:
  <<: *default

test:
  <<: *default

production:
  rss_service:
    host: <%= ENV['TEST_RSS_SERVICE_HOST'] %>
    auth_path: <%= ENV['TEST_RSS_SERVICE_PATH'] %>
    login: <%= ENV['TEST_RSS_SERVICE_LOGIN'] %>
    password: <%= ENV['TEST_RSS_SERVICE_PASSWORD'] %>
